POST localhost:8081/api/tasks
Content-Type: application/json

{
  "title": "Walk into forest",
  "description": "Walk",
  "author": "nobody"
}

###
GET localhost:8081/api/tasks

###
GET localhost:8081/api/tasks/1

###
DELETE localhost:8081/api/tasks/1

###
#PUT localhost:8081/api/tasks/1